# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7950f48ed515debce7393b9e7aee8620299e6421289567208922628bbd896f477f23316c93c6233fd1ec6426e2a2241721ae0a6b15935a0be0c745b3a6c47326

test:
  secret_key_base: e0c97e8e2ae9ad80014dc18201e3e93bef5fc5c7204d17023aa5fdeb4b252a0b4984029815bdbcbcb25650ab3982aa7b01b17c508862b48c2b740b3c2da1b500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
